### ISSUE TITLE
Problems with running ref_inpainting_gradio.py

### ISSUE THREAD

**Issue by YouXMu** [ewrfcas/LeftRefill#6]
Hello! when I want to run the ref_inpainting_gradio.py file, I get the following error, as I am using the gradio library for the first time, can you give me some advices for this problem? I am using xshell to connect to the remote server to run this .py file.
![image](https://github.com/ewrfcas/LeftRefill/assets/102397437/eed2681a-f7bd-4d3b-9aa7-bb8ca32d7dc2)

**Comment by ewrfcas** [comment]
This should be the timeout issue. Please see https://hf-mirror.com/ for more helps.

**Comment by YouXMu** [comment]
Thank you for your reply, I changed the version of gradio I downloaded and eventually solved the problem.
Inpainting looks good. Thanks a lot!
